/*

 WOTest_Version.h
 WOTest

 Created by Wincent Colaiuta on 26 March 2007.

 Copyright 2007 Wincent Colaiuta.
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 Do not edit this file: it is automatically updated each build via a script

 */

/* START: Auto-updated macro definitions */

#define WO_COPYRIGHT_YEAR   2004-2009

/* END: Auto-updated macro definitons */

/*!

The publicly visible "marketing" version, updated manually.

\bug Must perform a "Clean" or "Clean All" in order for changes to this macro to be picked up by the UpdateBuildVersionNumbers.sh script.

*/
#define WO_INFO_PLIST_VERSION       1.99-pre    /* Leopard version will eventually become 2.0 */

/*! Stringification macro. Turns macro EXAMPLE into string "EXAMPLE". */
#define WO_STRINGIFY(var)           #var

/*! Double-stringification macro. Turns macro EXAMPLE into string "contents of EXAMPLE macro after expansion". */
#define WO_STRINGIFY_TWICE(var)     WO_STRINGIFY(var)

#define WO_MARKETINGVERSION         WO_STRINGIFY_TWICE(WO_INFO_PLIST_VERSION)
#define WO_COPYRIGHT_YEAR_STRING    WO_STRINGIFY_TWICE(WO_COPYRIGHT_YEAR)
#define WO_COPYRIGHT                "Copyright " WO_COPYRIGHT_YEAR_STRING " Wincent Colaiuta"

/*! Make what(1) produce meaningful output. Defines an id string accesible via "rcsid". The "used" attribute prevents the linker from removing the symbol during dead code stripping. */
#define WO_RCSID(msg)                                                       \
static const char *const rcsid[] __attribute__((used)) =            \
{ (char *)rcsid, "\100(#)" msg }

/*! Make what(1) produce meaningful output. Defines a tagged string accesible via "rcsid_tag". The "used" attribute prevents the linker from removing the symbol during dead code stripping. */
#define WO_TAGGED_RCSID(msg, tag)                                           \
static const char *const rcsid_ ## tag[] __attribute__((used)) =    \
{ (char *)rcsid_ ## tag, "\100(#)" msg }

/*! Convenience macro for accessing a string previously created with WO_TAGGED_RCSID. */
#define WO_RCSID_STRING(tag) (rcsid_ ## tag[1] + 4)

#ifndef WO_PREPROCESSING_FOR_INFO_PLIST

WO_TAGGED_RCSID(WO_COPYRIGHT, copyright);

#if defined(__ppc__)
WO_TAGGED_RCSID("Architecture: PowerPC (ppc)", architecture);
#elif defined(__ppc64__)
WO_TAGGED_RCSID("Architecture: PowerPC (ppc64)", architecture);
#elif defined(__i386__)
WO_TAGGED_RCSID("Architecture: Intel (i386)", architecture);
#elif defined(__x86_64__)
WO_TAGGED_RCSID("Architecture: Intel (x86_64)", architecture);
#endif

WO_TAGGED_RCSID("Version: " WO_MARKETINGVERSION, version);
WO_TAGGED_RCSID("WOTest Framework", productname);

#endif /* WO_PREPROCESSING_FOR_INFO_PLIST */
